FROM ruby:2.3 
MAINTAINER "chris evett" <chris.evett@gmail.com>
COPY . /opt/poolsclosed/
RUN ls -al /opt/poolsclosed

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES true

RUN bundle install --gemfile=/opt/poolsclosed/Gemfile

RUN echo "#!/usr/bin/env bash" >> /opt/startup.sh
RUN echo "pushd /opt/poolsclosed" >> /opt/startup.sh
RUN echo "ruby -Ilib bin/poolsclosed" >> /opt/startup.sh
RUN chmod +x /opt/startup.sh

EXPOSE 42069

WORKDIR "/opt/poolsclosed"
CMD ["/opt/startup.sh"]
